### ISSUE TITLE
fcmex doesn't compile with retry v 0.10.0

### ISSUE THREAD

**Issue by nietaki** [shufo/fcmex#8]
Here's a repro:

```bash
[I] ~/r/fcmex (master|✔) $ mix compile
==> exactor
Compiling 10 files (.ex)
Generated exactor app
# lots of lines cut
Generated credo app
==> fcmex
Compiling 6 files (.ex)
Generated fcmex app
[I] ~/r/fcmex (master|✔) $ mix deps.update retry
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  bunt 0.2.0
  certifi 1.2.1
  credo 0.8.1
  earmark 1.2.2
  ex_doc 0.16.1
  exactor 2.2.3
  excoveralls 0.7.0
  exjsx 3.2.1
  exvcr 0.8.10
  flow 0.12.0
  gen_stage 0.12.0 RETIRED!
    (invalid) Cancel and info messages in producer_consumer can be delivered out of order, leading to data loss
  hackney 1.8.6
  httpoison 0.11.2
  idna 5.0.2
  jsx 2.8.2
  meck 0.8.4
  metrics 1.0.1
  mimerl 1.0.2
  poison 3.1.0
  ssl_verify_fun 1.1.1
  unicode_util_compat 0.2.0
Upgraded:
  retry 0.7.0 => 0.10.0
* Updating retry (Hex package)
[I] ~/r/fcmex (master|✚1…) $ mix compile
==> retry
Compiling 2 files (.ex)
Generated retry app
==> fcmex
Compiling 6 files (.ex)

== Compilation error in file lib/fcmex/subscription.ex ==
** (ArgumentError) invalid syntax, only "retry", "after" and "else" are permitted
    expanding macro: Retry.retry/2
    lib/fcmex/subscription.ex:66: Fcmex.Subscription.request/1
    (elixir) expanding macro: Kernel.|>/2
    lib/fcmex/subscription.ex:69: Fcmex.Subscription.request/1
[I] ~/r/fcmex (master|✚1…) [1] $
```

It popped up in our project when we were using fcmex as a dependency because we didn't have `retry` locked to an earlier version.

I'm going to look at what's causing it and see if there's an obvious fix, just raising it as an issue for now.
